name: Docker packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerBuildAndPush:
    name: Build Image and Publish to Docker Hub

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read version
      run: |
        export VERTAG=`cat RELEASE`
        echo "RELEASE_TAG=$VERTAG" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Container build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            zlatkoa/pgreeter:${{ env.RELEASE_TAG }}
